### ISSUE TITLE
[Feature request] Any chance for a self-hosted version?

### ISSUE THREAD

**Issue by Nebarik** [webrcade/webrcade-docs#1]
Came here from Retro Game Corps. 
Love the concept of this. But I'm always a little worried about services such as this going down. 

Are there any plans to release this for self hosting, perhaps as a docker image?
Even better if we can configure a custom default json feed, or even User support (might be getting a little ahead of myself with that one).

Thanks,

**Comment by microSCOPED** [comment]
Docker image exists - https://hub.docker.com/r/webrcade/webrcade

**Comment by KingIzzymon** [comment]
It can be deployed via Docker CLI by running:

```sh
docker run -d \
  --name=webrcade \
  -p 80:80 \
  --restart unless-stopped \
  webrcade/webrcade:latest
```

Or with docker-compose:

```yaml
version: "3"
services:
  webrcade:
    image: webrcade/webrcade:latest
    container_name: webrcade
    ports:
      - 80:80
    restart: unless-stopped
```

Accessible on the server at http://localhost/
